var district = [
    {
        url:'https://coronaharyana.in/?city=1',
        name:'Ambala'
    },
    {
        url:'https://coronaharyana.in/?city=2',
        name:'Bhiwani'
    },
    {
        url:'https://coronaharyana.in/?city=24',
        name:'Chandigarh'
    },
    {
        url:'https://coronaharyana.in/?city=3',
        name:'Charki Dadri'
    },
    {
        url:'https://coronaharyana.in/?city=4',
        name:'Faridabad'
    },
    {
        url:'https://coronaharyana.in/?city=5',
        name:'Fatehabad'
    },
    {
        url:'https://coronaharyana.in/?city=6',
        name:'Gurugram'
    },
    {
        url:'https://coronaharyana.in/?city=7',
        name:'Hisar'
    },
    {
        url:'https://coronaharyana.in/?city=8',
        name:'Jhajjar'
    },
    {
        url:'https://coronaharyana.in/?city=9',
        name:'Jind'
    },
    {
        url:'https://coronaharyana.in/?city=10',
        name:'Kaithal'
    },
    {
        url:'https://coronaharyana.in/?city=11',
        name:'Karnal'
    },
    {
        url:'https://coronaharyana.in/?city=12',
        name:'Kurukshetra'
    },
    {
        url:'https://coronaharyana.in/?city=13',
        name:'Mahendragarh'
    },
    {
        url:'https://coronaharyana.in/?city=14',
        name:'Ambala'
    },
    {
        url:'https://coronaharyana.in/?city=23',
        name:'Nuh'
    },
    {
        url:'https://coronaharyana.in/?city=15',
        name:'Palwal'
    },
    {
        url:'https://coronaharyana.in/?city=16',
        name:'Panchkula'
    },
    {
        url:'https://coronaharyana.in/?city=17',
        name:'Panipat'
    },
    {
        url:'https://coronaharyana.in/?city=18',
        name:'Rewari'
    },
    {
        url:'https://coronaharyana.in/?city=19',
        name:'Rohtak'
    },
    {
        url:'https://coronaharyana.in/?city=20',
        name:'Sirsa'
    },
    {
        url:'https://coronaharyana.in/?city=21',
        name:'Sonipat'
    },
    {
        url:'https://coronaharyana.in/?city=22',
        name:'Yamunanagar'
    }

]


exports.haryana = district